{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aigateway-portal.backend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
{{- end }}
