{{- if .Values.backend.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aigateway-portal.backend.fullname" . }}-model-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
rules:
  - apiGroups:
      - extensions.higress.io
    resources:
      - wasmplugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.higress.io
    resources:
      - mcpbridges
    verbs:
      - get
      - list
      - watch
{{- end }}
