{{- if and .Values.database.createSecret (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aigateway-portal.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.usernameKey }}: {{ .Values.database.username | quote }}
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | quote }}
  {{ .Values.database.databaseKey }}: {{ .Values.database.name | quote }}
{{- end }}
