apiVersion: v1
kind: Service
metadata:
  name: {{ include "aigateway-portal.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: {{ include "aigateway-portal.service.type" . }}
  ports:
    - port: {{ include "aigateway-portal.service.port" . | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aigateway-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
