{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aigateway-portal-mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "aigateway-portal-mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "aigateway-portal-mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
