// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalInvoiceProfile defines the fields of table "portal_invoice_profile" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalInvoiceProfile = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"consumer_name": {
		Index:   1,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"company_name": {
		Index:   2,
		Name:    "company_name",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"tax_no": {
		Index:   3,
		Name:    "tax_no",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"address": {
		Index:   4,
		Name:    "address",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"bank_account": {
		Index:   5,
		Name:    "bank_account",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"receiver": {
		Index:   6,
		Name:    "receiver",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"email": {
		Index:   7,
		Name:    "email",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"updated_at": {
		Index:   9,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
}

// SetPortalInvoiceProfileTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalInvoiceProfileTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_invoice_profile", PortalInvoiceProfile, schema...)
}
