// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalRechargeOrder defines the fields of table "portal_recharge_order" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalRechargeOrder = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"order_id": {
		Index:   1,
		Name:    "order_id",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"consumer_name": {
		Index:   2,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"amount": {
		Index:   3,
		Name:    "amount",
		Type:    "decimal(18,2)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"channel": {
		Index:   4,
		Name:    "channel",
		Type:    "varchar(32)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   5,
		Name:    "status",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   6,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
}

// SetPortalRechargeOrderTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalRechargeOrderTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_recharge_order", PortalRechargeOrder, schema...)
}
