// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalApiKey defines the fields of table "portal_api_key" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalApiKey = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"key_id": {
		Index:   1,
		Name:    "key_id",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"consumer_name": {
		Index:   2,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   3,
		Name:    "name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"key_masked": {
		Index:   4,
		Name:    "key_masked",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"key_hash": {
		Index:   5,
		Name:    "key_hash",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"raw_key": {
		Index:   6,
		Name:    "raw_key",
		Type:    "varchar(256)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   7,
		Name:    "status",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: "active",
		Extra:   "",
		Comment: "",
	},
	"total_calls": {
		Index:   8,
		Name:    "total_calls",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"last_used_at": {
		Index:   9,
		Name:    "last_used_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   10,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"updated_at": {
		Index:   11,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
}

// SetPortalApiKeyTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalApiKeyTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_api_key", PortalApiKey, schema...)
}
