// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalInvoiceRecord defines the fields of table "portal_invoice_record" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalInvoiceRecord = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"invoice_id": {
		Index:   1,
		Name:    "invoice_id",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"consumer_name": {
		Index:   2,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"title": {
		Index:   3,
		Name:    "title",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"tax_no": {
		Index:   4,
		Name:    "tax_no",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"amount": {
		Index:   5,
		Name:    "amount",
		Type:    "decimal(18,2)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   6,
		Name:    "status",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"remark": {
		Index:   7,
		Name:    "remark",
		Type:    "varchar(512)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   8,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
}

// SetPortalInvoiceRecordTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalInvoiceRecordTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_invoice_record", PortalInvoiceRecord, schema...)
}
