// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalUsageDaily defines the fields of table "portal_usage_daily" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalUsageDaily = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"billing_date": {
		Index:   1,
		Name:    "billing_date",
		Type:    "date",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"consumer_name": {
		Index:   2,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"model_name": {
		Index:   3,
		Name:    "model_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"request_count": {
		Index:   4,
		Name:    "request_count",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"input_tokens": {
		Index:   5,
		Name:    "input_tokens",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"output_tokens": {
		Index:   6,
		Name:    "output_tokens",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"total_tokens": {
		Index:   7,
		Name:    "total_tokens",
		Type:    "bigint",
		Null:    false,
		Key:     "",
		Default: "0",
		Extra:   "",
		Comment: "",
	},
	"cost_amount": {
		Index:   8,
		Name:    "cost_amount",
		Type:    "decimal(18,6)",
		Null:    false,
		Key:     "",
		Default: "0.000000",
		Extra:   "",
		Comment: "",
	},
	"source_from": {
		Index:   9,
		Name:    "source_from",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"source_to": {
		Index:   10,
		Name:    "source_to",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   11,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"updated_at": {
		Index:   12,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
}

// SetPortalUsageDailyTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalUsageDailyTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_usage_daily", PortalUsageDaily, schema...)
}
