// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalSession defines the fields of table "portal_session" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalSession = map[string]*gdb.TableField{
	"session_token": {
		Index:   0,
		Name:    "session_token",
		Type:    "varchar(96)",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"consumer_name": {
		Index:   1,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"expires_at": {
		Index:   2,
		Name:    "expires_at",
		Type:    "datetime",
		Null:    false,
		Key:     "MUL",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   3,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"last_seen_at": {
		Index:   4,
		Name:    "last_seen_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
}

// SetPortalSessionTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalSessionTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_session", PortalSession, schema...)
}
