// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalModelCatalog defines the fields of table "portal_model_catalog" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalModelCatalog = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"model_id": {
		Index:   1,
		Name:    "model_id",
		Type:    "varchar(64)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"name": {
		Index:   2,
		Name:    "name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"vendor": {
		Index:   3,
		Name:    "vendor",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"capability": {
		Index:   4,
		Name:    "capability",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"input_token_price": {
		Index:   5,
		Name:    "input_token_price",
		Type:    "decimal(18,6)",
		Null:    false,
		Key:     "",
		Default: "0.000000",
		Extra:   "",
		Comment: "",
	},
	"output_token_price": {
		Index:   6,
		Name:    "output_token_price",
		Type:    "decimal(18,6)",
		Null:    false,
		Key:     "",
		Default: "0.000000",
		Extra:   "",
		Comment: "",
	},
	"endpoint": {
		Index:   7,
		Name:    "endpoint",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"sdk": {
		Index:   8,
		Name:    "sdk",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"summary": {
		Index:   9,
		Name:    "summary",
		Type:    "text",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   10,
		Name:    "status",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: "active",
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   11,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"updated_at": {
		Index:   12,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
}

// SetPortalModelCatalogTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalModelCatalogTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_model_catalog", PortalModelCatalog, schema...)
}
