// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package table

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

// PortalUser defines the fields of table "portal_user" with their properties.
// This map is used internally by GoFrame ORM to understand table structure.
var PortalUser = map[string]*gdb.TableField{
	"id": {
		Index:   0,
		Name:    "id",
		Type:    "bigint",
		Null:    false,
		Key:     "PRI",
		Default: nil,
		Extra:   "auto_increment",
		Comment: "",
	},
	"consumer_name": {
		Index:   1,
		Name:    "consumer_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "UNI",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"display_name": {
		Index:   2,
		Name:    "display_name",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"email": {
		Index:   3,
		Name:    "email",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"department": {
		Index:   4,
		Name:    "department",
		Type:    "varchar(128)",
		Null:    false,
		Key:     "",
		Default: "",
		Extra:   "",
		Comment: "",
	},
	"password_hash": {
		Index:   5,
		Name:    "password_hash",
		Type:    "varchar(255)",
		Null:    false,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"status": {
		Index:   6,
		Name:    "status",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: "active",
		Extra:   "",
		Comment: "",
	},
	"source": {
		Index:   7,
		Name:    "source",
		Type:    "varchar(16)",
		Null:    false,
		Key:     "",
		Default: "portal",
		Extra:   "",
		Comment: "",
	},
	"last_login_at": {
		Index:   8,
		Name:    "last_login_at",
		Type:    "datetime",
		Null:    true,
		Key:     "",
		Default: nil,
		Extra:   "",
		Comment: "",
	},
	"created_at": {
		Index:   9,
		Name:    "created_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED",
		Comment: "",
	},
	"updated_at": {
		Index:   10,
		Name:    "updated_at",
		Type:    "datetime",
		Null:    false,
		Key:     "",
		Default: "CURRENT_TIMESTAMP",
		Extra:   "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
		Comment: "",
	},
}

// SetPortalUserTableFields registers the table fields definition to the database instance.
// db: database instance that implements gdb.DB interface.
// schema: optional schema/namespace name, especially for databases that support schemas.
func SetPortalUserTableFields(ctx context.Context, db gdb.DB, schema ...string) error {
	return db.GetCore().SetTableFields(ctx, "portal_user", PortalUser, schema...)
}
