// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalSessionDao is the data access object for the table portal_session.
// You can define custom methods on it to extend its functionality as needed.
type portalSessionDao struct {
	*internal.PortalSessionDao
}

var (
	// PortalSession is a globally accessible object for table portal_session operations.
	PortalSession = portalSessionDao{internal.NewPortalSessionDao()}
)

// Add your custom methods and functionality below.
