// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalUserDao is the data access object for the table portal_user.
// You can define custom methods on it to extend its functionality as needed.
type portalUserDao struct {
	*internal.PortalUserDao
}

var (
	// PortalUser is a globally accessible object for table portal_user operations.
	PortalUser = portalUserDao{internal.NewPortalUserDao()}
)

// Add your custom methods and functionality below.
