// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalRechargeOrderDao is the data access object for the table portal_recharge_order.
// You can define custom methods on it to extend its functionality as needed.
type portalRechargeOrderDao struct {
	*internal.PortalRechargeOrderDao
}

var (
	// PortalRechargeOrder is a globally accessible object for table portal_recharge_order operations.
	PortalRechargeOrder = portalRechargeOrderDao{internal.NewPortalRechargeOrderDao()}
)

// Add your custom methods and functionality below.
