// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalInvoiceProfileDao is the data access object for the table portal_invoice_profile.
// You can define custom methods on it to extend its functionality as needed.
type portalInvoiceProfileDao struct {
	*internal.PortalInvoiceProfileDao
}

var (
	// PortalInvoiceProfile is a globally accessible object for table portal_invoice_profile operations.
	PortalInvoiceProfile = portalInvoiceProfileDao{internal.NewPortalInvoiceProfileDao()}
)

// Add your custom methods and functionality below.
