// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalApiKeyDao is the data access object for the table portal_api_key.
// You can define custom methods on it to extend its functionality as needed.
type portalApiKeyDao struct {
	*internal.PortalApiKeyDao
}

var (
	// PortalApiKey is a globally accessible object for table portal_api_key operations.
	PortalApiKey = portalApiKeyDao{internal.NewPortalApiKeyDao()}
)

// Add your custom methods and functionality below.
