// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalModelCatalogDao is the data access object for the table portal_model_catalog.
// You can define custom methods on it to extend its functionality as needed.
type portalModelCatalogDao struct {
	*internal.PortalModelCatalogDao
}

var (
	// PortalModelCatalog is a globally accessible object for table portal_model_catalog operations.
	PortalModelCatalog = portalModelCatalogDao{internal.NewPortalModelCatalogDao()}
)

// Add your custom methods and functionality below.
