// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalUsageDailyDao is the data access object for the table portal_usage_daily.
// You can define custom methods on it to extend its functionality as needed.
type portalUsageDailyDao struct {
	*internal.PortalUsageDailyDao
}

var (
	// PortalUsageDaily is a globally accessible object for table portal_usage_daily operations.
	PortalUsageDaily = portalUsageDailyDao{internal.NewPortalUsageDailyDao()}
)

// Add your custom methods and functionality below.
