// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalInviteCodeDao is the data access object for the table portal_invite_code.
// You can define custom methods on it to extend its functionality as needed.
type portalInviteCodeDao struct {
	*internal.PortalInviteCodeDao
}

var (
	// PortalInviteCode is a globally accessible object for table portal_invite_code operations.
	PortalInviteCode = portalInviteCodeDao{internal.NewPortalInviteCodeDao()}
)

// Add your custom methods and functionality below.
