// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"higress-portal-backend/internal/dao/internal"
)

// portalInvoiceRecordDao is the data access object for the table portal_invoice_record.
// You can define custom methods on it to extend its functionality as needed.
type portalInvoiceRecordDao struct {
	*internal.PortalInvoiceRecordDao
}

var (
	// PortalInvoiceRecord is a globally accessible object for table portal_invoice_record operations.
	PortalInvoiceRecord = portalInvoiceRecordDao{internal.NewPortalInvoiceRecordDao()}
)

// Add your custom methods and functionality below.
